### ISSUE TITLE
FileNotFoundError: [Errno 2] could not open alignment file `intermediate_files/reference_all_to_target_all.sam`: No such file or directory

### ISSUE THREAD

**Issue by rkadrian** [agshumate/Liftoff#126]
I am having the same error as previously submitted 3 July 2020, but I have no yet been able to fix it. I am running minimap2 v. 2.1.3 and Liftoff v. 1.6.3.
Here is the error output (minus a populating features line that is VERY long):

2022-08-09 12:02:53,564 - INFO - Populating features
[line removed]
2022-08-09 12:04:39,602 - INFO - Updating relations
2022-08-09 12:05:01,812 - INFO - Creating relations(parent) index
2022-08-09 12:05:05,165 - INFO - Creating relations(child) index
2022-08-09 12:05:09,079 - INFO - Creating features(featuretype) index
2022-08-09 12:05:12,933 - INFO - Creating features (seqid, start, end) index
2022-08-09 12:05:13,735 - INFO - Creating features (seqid, start, end, strand) index
2022-08-09 12:05:14,609 - INFO - Running ANALYZE features
[ERROR] unknown option in "intermediate_files/reference_all_to_target_all.sam"
[E::hts_open_format] Failed to open file "intermediate_files/reference_all_to_target_all.sam" : No such file or directory
Traceback (most recent call last):
  File "/home/rea4110/.local/bin/liftoff", line 8, in <module>
    sys.exit(main())
  File "/home/rea4110/.local/lib/python3.8/site-packages/liftoff/run_liftoff.py", line 12, in main
    run_all_liftoff_steps(args)
  File "/home/rea4110/.local/lib/python3.8/site-packages/liftoff/run_liftoff.py", line 24, in run_all_liftoff_steps
    feature_db, feature_hierarchy, ref_parent_order = liftover_types.lift_original_annotation(ref_chroms, target_chroms,
  File "/home/rea4110/.local/lib/python3.8/site-packages/liftoff/liftover_types.py", line 15, in lift_original_annotation
    align_and_lift_features(ref_chroms, target_chroms, args, feature_hierarchy, liftover_type, unmapped_features,
  File "/home/rea4110/.local/lib/python3.8/site-packages/liftoff/liftover_types.py", line 23, in align_and_lift_features
    aligned_segments= align_features.align_features_to_target(ref_chroms, target_chroms, args,
  File "/home/rea4110/.local/lib/python3.8/site-packages/liftoff/align_features.py", line 28, in align_features_to_target
    return parse_all_sam_files(feature_hierarchy, unmapped_features, liftover_type, sam_files)
  File "/home/rea4110/.local/lib/python3.8/site-packages/liftoff/align_features.py", line 118, in parse_all_sam_files
    aligned_segments = parse_alignment(file, feature_hierarchy, unmapped_features, liftover_type)
  File "/home/rea4110/.local/lib/python3.8/site-packages/liftoff/align_features.py", line 125, in parse_alignment
    sam_file = pysam.AlignmentFile(file, 'r', check_sq=False, check_header=False)
  File "pysam/libcalignmentfile.pyx", line 742, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 941, in pysam.libcalignmentfile.AlignmentFile._open
FileNotFoundError: [Errno 2] could not open alignment file `intermediate_files/reference_all_to_target_all.sam`: No such file or directory

The previous poster from 2020 solved the problem by adjusting the FASTA line width to 80. I tried this just in case, but no luck, yet. The "reference_all_genes.fa" file appears to be successfully created in the intermediate files folder, but no .sam file. I am working with an as-yet unpublished genome and attempting to liftover from a close relative.

Any advice very much appreciated. Thank you!

**Comment by agshumate** [comment]
hi, are you still having this issue?

**Comment by rkadrian** [comment]
Yes, but I'm going to try running locally as it might be a product of the remote system I was working on. A friend was able to complete the liftoff on his system correctly. Thank you!

**Comment by zpliu1126** [comment]
> 



> hi, are you still having this issue?

Hi，I meet the same problems. I guess it may be caused by the same chromosome Id in the fasta file of refere  and targe. After
I chage this Id, it work for me

**Comment by nkschaefer** [comment]
If it's helpful to anyone, I fixed this issue on my machine by getting a newer version of minimap2. conda had automatically installed 2.1.1-r341, and I noticed this and several other errors related to minimap2 arguments. conda install -c bioconda minimap2=2.28 fixed it for me.
