### ISSUE TITLE
Issue with running Liftoff

### ISSUE THREAD

**Issue by dalila-de** [agshumate/Liftoff#127]
Hi,

I've been facing this error when trying to run Liftoff:

`2022-08-23 22:00:39,770 - INFO - Populating features table and first-order relations: 1546645 features
2022-08-23 22:00:39,778 - INFO - Creating relations(parent) index
2022-08-23 22:00:43,513 - INFO - Creating relations(child) index
2022-08-23 22:00:46,972 - INFO - Creating features(featuretype) index
2022-08-23 22:00:50,003 - INFO - Creating features (seqid, start, end) index
2022-08-23 22:00:52,666 - INFO - Creating features (seqid, start, end, strand) index
2022-08-23 22:00:55,446 - INFO - Running ANALYZE features
extracting features
Traceback (most recent call last):
  File "/scratch/students/Octopus_v_proj/miniconda3/envs/env_liftoff/bin/liftoff", line 33, in <module>
    sys.exit(load_entry_point('Liftoff==1.6.3', 'console_scripts', 'liftoff')())
  File "/scratch/students/Octopus_v_proj/miniconda3/envs/env_liftoff/lib/python3.9/site-packages/Liftoff-1.6.3-py3.9.egg/liftoff/run_liftoff.py", line 12, in main
  File "/scratch/students/Octopus_v_proj/miniconda3/envs/env_liftoff/lib/python3.9/site-packages/Liftoff-1.6.3-py3.9.egg/liftoff/run_liftoff.py", line 24, in run_all_liftoff_steps
  File "/scratch/students/Octopus_v_proj/miniconda3/envs/env_liftoff/lib/python3.9/site-packages/Liftoff-1.6.3-py3.9.egg/liftoff/liftover_types.py", line 11, in lift_original_annotation
  File "/scratch/students/Octopus_v_proj/miniconda3/envs/env_liftoff/lib/python3.9/site-packages/Liftoff-1.6.3-py3.9.egg/liftoff/extract_features.py", line 18, in extract_features_to_lift
  File "/scratch/students/Octopus_v_proj/miniconda3/envs/env_liftoff/lib/python3.9/site-packages/Liftoff-1.6.3-py3.9.egg/liftoff/extract_features.py", line 80, in seperate_parents_and_children
  File "/scratch/students/Octopus_v_proj/miniconda3/envs/env_liftoff/lib/python3.9/site-packages/Liftoff-1.6.3-py3.9.egg/liftoff/extract_features.py", line 105, in add_children
sqlite3.OperationalError: near "Covext": syntax error`

Does anybody have an idea what might be causing this? 

Thanks in advance!

**Comment by agshumate** [comment]
can you please send the command you are using?

**Comment by dalila-de** [comment]
Hi,

Thanks for responding!

I'm using this command:

`liftoff -g ${ADDRESS}Data_S1.3_prime_extended_genome_annotation.gtf ${ADDRESS}octopus_vulgaris_v4.fasta ${ADDRESS}GCF_006345805.1_ASM634580v1_genomic.fna`

**Comment by agshumate** [comment]
was the _db file properly created. if so what is its name?

**Comment by dalila-de** [comment]
I assume it was because it takes up 1.1GB of memory. The name is Data_S1.3_prime_extended_genome_annotation.gtf_db

**Comment by agshumate** [comment]
can you try deleting that file and re-running liftoff?

**Comment by dalila-de** [comment]
Thanks for the suggestion. I've tried it, but I got the same error again.

**Comment by pur80a** [comment]
Hi,

On the same machine I get: 
```
Traceback (most recent call last):
  File "/apps/liftoff/1.5.1/bin/liftoff", line 8, in <module>
    sys.exit(main())
  File "/apps/liftoff/1.5.1/lib/python3.8/site-packages/liftoff/run_liftoff.py", line 16, in main
    feature_db, feature_hierarchy, ref_parent_order = liftover_types.lift_original_annotation(ref_chroms, target_chroms,
  File "/apps/liftoff/1.5.1/lib/python3.8/site-packages/liftoff/liftover_types.py", line 11, in lift_original_annotation
    feature_hierarchy, feature_db, ref_parent_order = extract_features.extract_features_to_lift(ref_chroms,
  File "/apps/liftoff/1.5.1/lib/python3.8/site-packages/liftoff/extract_features.py", line 17, in extract_features_to_lift
    feature_db, feature_db_name = create_feature_db_connections(args)
  File "/apps/liftoff/1.5.1/lib/python3.8/site-packages/liftoff/extract_features.py", line 44, in create_feature_db_connections
    return feature_db, feature_db_name
UnboundLocalError: local variable 'feature_db' referenced before assignment
```
I had a look at `extract_features.py` and the function: 
```
def build_database(db, gff_file, disable_transcripts, disable_genes,):
    if db is None:
        try:
            feature_db = gffutils.create_db(gff_file, gff_file + "_db", merge_strategy="create_unique", force=True,
                                            disable_infer_transcripts=disable_transcripts,
                                            disable_infer_genes=disable_genes, verbose=True)
        except:
            find_problem_line(gff_file)
    else:
        feature_db = gffutils.FeatureDB(db)
    return feature_db
```
It seems that neither `try` nor `except` is executed as I don't get any output from those functions. 
We upgraded from CentOS 7 to Oracle Linux 8 some time ago. And python version < 3.10 were installed on the old OS. 
Could it be that a library is missing? 

Thanks and all the best
