### ISSUE TITLE
Error running analyze features 

### ISSUE THREAD

**Issue by fishercera** [agshumate/Liftoff#135]
Hi Dr. Shumate, 

I'm actually having the same problem as user @pur80a downthread in issue #127 but I'm opening a separate issue because I don't believe that their problem is the same as the original issue in that thread. 

I installed liftoff with conda, but had to isntall liftools by cloning the repo and installing with the setup.py. I installed dependency mmseq2 by as a precompiled binary. I'm running in Ubuntu on Windows subsystem for linux, arch is x86_64. 

Command I'm running is: 
`liftofftools all -r $REFERENCE -t $TARGET -rg $REFANNOTS -tg $TARGANNOTS -dir Chrom1_liftofftools_out`

Here is the error output that I get:
```
2022-09-28 10:51:03,586 - INFO - Running ANALYZE features
/usr/local/lib/python3.8/dist-packages/gffutils-0.11.0-py3.8.egg/gffutils/create.py:770: UserWarning: It appears you have a gene feature in your GTF file. You may want to use the `disable_infer_genes=True` option to speed up database creation
  warnings.warn(
1 of 2 (50%)
1 of 2 (50%)
0 of 2 (0%))
1 of 2 (50%)
1 of 2 (50%)


Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/LiftoffTools-0.4.3-py3.8.egg/liftofftools/annotation.py", line 17, in get_db_connnection
  File "/usr/local/lib/python3.8/dist-packages/gffutils-0.11.0-py3.8.egg/gffutils/interface.py", line 196, in __init__
    c.execute(
sqlite3.DatabaseError: file is not a database

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/liftofftools", line 11, in <module>
    load_entry_point('LiftoffTools==0.4.3', 'console_scripts', 'liftofftools')()
  File "/usr/local/lib/python3.8/dist-packages/LiftoffTools-0.4.3-py3.8.egg/liftofftools/liftofftools.py", line 19, in main
  File "/usr/local/lib/python3.8/dist-packages/LiftoffTools-0.4.3-py3.8.egg/liftofftools/annotation.py", line 12, in __init__
  File "/usr/local/lib/python3.8/dist-packages/LiftoffTools-0.4.3-py3.8.egg/liftofftools/annotation.py", line 19, in get_db_connnection
  File "/usr/local/lib/python3.8/dist-packages/LiftoffTools-0.4.3-py3.8.egg/liftofftools/annotation.py", line 37, in build_database
UnboundLocalError: local variable 'feature_db' referenced before assignment
```

*reproducibility:* 

This error _does not occur_ when I run the same command on a smaller dataset, made from just the first 5000 lines of each of my reference/target annotation files. In that case, this is the output:

```
2022-09-28 12:35:42,966 - INFO - Committing changes: 4000 features
2022-09-28 12:35:42,988 - INFO - Populating features table and first-order relations: 4995 features
2022-09-28 12:35:42,989 - INFO - Creating relations(parent) index
2022-09-28 12:35:42,991 - INFO - Creating relations(child) index
2022-09-28 12:35:42,994 - INFO - Creating features(featuretype) index
2022-09-28 12:35:42,996 - INFO - Creating features (seqid, start, end) index
2022-09-28 12:35:42,998 - INFO - Creating features (seqid, start, end, strand) index
2022-09-28 12:35:43,000 - INFO - Running ANALYZE features
2022-09-28 12:35:43,464 - INFO - Committing changes: 4000 features
2022-09-28 12:35:43,488 - INFO - Populating features table and first-order relations: 4997 features
2022-09-28 12:35:43,489 - INFO - Creating relations(parent) index
2022-09-28 12:35:43,491 - INFO - Creating relations(child) index
2022-09-28 12:35:43,495 - INFO - Creating features(featuretype) index
2022-09-28 12:35:43,497 - INFO - Creating features (seqid, start, end) index
2022-09-28 12:35:43,498 - INFO - Creating features (seqid, start, end, strand) index
2022-09-28 12:35:43,500 - INFO - Running ANALYZE features
Analyzing synteny
Extracting transcript sequences
Analyzing protein-coding clusters
Analyzing noncoding clusters
Analyzing variants
```

Additional information: 
After a failed run, there is a file in the working directory named `:memory` which is about 68 MiB. There are, additionally, two *.gff_db files created, one for my target and one reference, but the target .gff_db file is much smaller, which makes me think it's truncated. 

Also, in my liftoff run, I permitted identification of copies, because I have reason to think that there are duplications in my target, and I allowed 100% overlap of genes, because I know that that happens in my organism (there are tRNAs in the annotation that fall within introns of other genes; these mosquitos have insanely big introns).  Is it possible that either of these things are causing an issue? It really looks like what's happening is that the database creation process gets stopped at a particular point. I'm considering chunking up my gff files and seeing if I can identify where it happens; that might be helpful.

**Comment by agshumate** [comment]
Hi,
Is your reference genome and annotation publicly available by chance so I can test it out on my end?

**Comment by fishercera** [comment]
Yes, reference genome and annotation are public. 

https://www.ncbi.nlm.nih.gov/genome/annotation_euk/Aedes_aegypti/101/ 

Do you need anything else for testing purposes? 

Sorry for not responding quickly. Liftoff is a great piece of software!

**Comment by agshumate** [comment]
Which specific reference annotation and assembly are you using? RefSeq or Genbank and GTF format or GFF format?

**Comment by fishercera** [comment]
RefSeq, GTF format - GCF_002204515.2_AaegL5.0_genomic.gtf

(Also, my apologies, this probably should have been posted to the liftofftools repo, not this one)

**Comment by agshumate** [comment]
no problem. I was not able to reproduce this error on my end but I have a new version of LiftoffTools (0.4.4) that has better error handling. If you try running that new version and can tell me what the exact error youre getting is, I can hopefully be more helpful.

**Comment by fishercera** [comment]
Thanks so much. 

I'll update to the new version. I was able to get LiftoffTools to run nicely today; I ran Liftoff again with a different version of the reference annotations, and leaving off the -copies option. I will be doing a little more testing and will be able to tell if the problem was related to having copies, to the annotation version, or just what exactly might have been happening. If I can discover anything useful, I'll pop back and let you know, but I'm willing to let this issue be closed now. :) Thanks so much for making such a useful piece of code!
