### ISSUE TITLE
ValueError: fetch called for htsfile without header

### ISSUE THREAD

**Issue by Zazzyre** [agshumate/Liftoff#160]
Hi,
I'm running into a fetch error when trying to run liftoff. It seems to build the index fine but have issues afterwards at the minimap2 intermediate files stage.Any help would be appriciated

The command line of the run is below:

(base) zazzy@pepper:~/liftoff$ liftoff -g /home/zazzy/Documents/Annotationsncbi/cvociferusanno/data/GCF_000708025.1/genomic.gff -o /home/zazzy/Documents/vociferustomontanus -u /home/zazzy/Documents/unmappedvociferustomontanus -exclude_partial -dir /home/zazzy/Documents/intermediateliftoff -p 4 -m /home/zazzy/minimap2/minimap2 -copies /home/zazzy/Downloads/Genomefiles/cmontanuswmitodeduped.fasta /home/zazzy/Documents/vociferus.fasta
extracting features
2024-01-10 10:07:43,756 - INFO - Populating features
2024-01-10 10:08:36,081 - INFO - Populating features table and first-order relations: 424720 features
2024-01-10 10:08:36,081 - INFO - Updating relations
2024-01-10 10:08:38,875 - INFO - Creating relations(parent) index
2024-01-10 10:08:39,062 - INFO - Creating relations(child) index
2024-01-10 10:08:39,319 - INFO - Creating features(featuretype) index
2024-01-10 10:08:39,508 - INFO - Creating features (seqid, start, end) index
2024-01-10 10:08:39,748 - INFO - Creating features (seqid, start, end, strand) index
2024-01-10 10:08:40,002 - INFO - Running ANALYZE features
aligning features
[M::main::9.097*0.80] loaded/built the index for 3790 target sequence(s)
[M::mm_mapopt_update::10.279*0.82] mid_occ = 182
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 3790
[M::mm_idx_stat::11.130*0.84] distinct minimizers: 80969340 (48.96% are singletons); average occurrences: 3.019; average spacing: 5.339; total length: 1305019834
[M::worker_pipeline::85.099*3.38] mapped 14670 sequences
[M::main] Version: 2.26-r1175
[M::main] CMD: /home/zazzy/minimap2/minimap2 -o /home/zazzy/Documents/intermediateliftoff/reference_all_to_target_all.sam -a --end-bonus 5 --eqx -N 50 -p 0.5 -t 4 /home/zazzy/Downloads/Genomefiles/cmontanuswmitodeduped.fasta.mmi /home/zazzy/Documents/intermediateliftoff/reference_all_genes.fa
[M::main] Real time: 85.161 sec; CPU: 287.912 sec; Peak RSS: 7.281 GB
Traceback (most recent call last):
  File "/home/zazzy/anaconda3/bin/liftoff", line 33, in <module>
    sys.exit(load_entry_point('Liftoff==1.6.3', 'console_scripts', 'liftoff')())
  File "/home/zazzy/anaconda3/lib/python3.9/site-packages/Liftoff-1.6.3-py3.9.egg/liftoff/run_liftoff.py", line 12, in main
  File "/home/zazzy/anaconda3/lib/python3.9/site-packages/Liftoff-1.6.3-py3.9.egg/liftoff/run_liftoff.py", line 24, in run_all_liftoff_steps
  File "/home/zazzy/anaconda3/lib/python3.9/site-packages/Liftoff-1.6.3-py3.9.egg/liftoff/liftover_types.py", line 15, in lift_original_annotation
  File "/home/zazzy/anaconda3/lib/python3.9/site-packages/Liftoff-1.6.3-py3.9.egg/liftoff/liftover_types.py", line 23, in align_and_lift_features
  File "/home/zazzy/anaconda3/lib/python3.9/site-packages/Liftoff-1.6.3-py3.9.egg/liftoff/align_features.py", line 28, in align_features_to_target
  File "/home/zazzy/anaconda3/lib/python3.9/site-packages/Liftoff-1.6.3-py3.9.egg/liftoff/align_features.py", line 118, in parse_all_sam_files
  File "/home/zazzy/anaconda3/lib/python3.9/site-packages/Liftoff-1.6.3-py3.9.egg/liftoff/align_features.py", line 126, in parse_alignment
  File "pysam/calignmentfile.pyx", line 934, in pysam.calignmentfile.AlignmentFile.fetch
ValueError: fetch called for htsfile without header

**Comment by Zazzyre** [comment]
Uninstalling and using pip to install instead seemed to fix the issue
