### ISSUE TITLE
UnboundLocalError 

### ISSUE THREAD

**Issue by pdoris** [agshumate/Liftoff#175]
Traceback (most recent call last):t-order relations: 2374000 features                                                                 
  File "/home1/06127/pdoris/miniforge3/envs/liftoff/bin/liftoff", line 10, in <module>                                                
    sys.exit(main())                                                                                                                  
  File "/home1/06127/pdoris/miniforge3/envs/liftoff/lib/python3.8/site-packages/liftoff/run_liftoff.py", line 12, in main             
    run_all_liftoff_steps(args)                                                                                                       
  File "/home1/06127/pdoris/miniforge3/envs/liftoff/lib/python3.8/site-packages/liftoff/run_liftoff.py", line 24, in run_all_liftoff_steps                                                                                                                                  
    feature_db, feature_hierarchy, ref_parent_order = liftover_types.lift_original_annotation(ref_chroms, target_chroms,              
  File "/home1/06127/pdoris/miniforge3/envs/liftoff/lib/python3.8/site-packages/liftoff/liftover_types.py", line 11, in lift_original_annotation                                                                                                                            
    feature_hierarchy, feature_db, ref_parent_order = extract_features.extract_features_to_lift(ref_chroms,                           
  File "/home1/06127/pdoris/miniforge3/envs/liftoff/lib/python3.8/site-packages/liftoff/extract_features.py", line 17, in extract_features_to_lift                                                                                                                          
    feature_db = create_feature_db_connections(args)                                                                                  
  File "/home1/06127/pdoris/miniforge3/envs/liftoff/lib/python3.8/site-packages/liftoff/extract_features.py", line 33, in create_feature_db_connections
    feature_db = build_database(args.db, args.g, disable_transcripts, disable_genes)
  File "/home1/06127/pdoris/miniforge3/envs/liftoff/lib/python3.8/site-packages/liftoff/extract_features.py", line 48, in build_database
    return feature_db
UnboundLocalError: local variable 'feature_db' referenced before assignment

**Comment by haydenji0731** [comment]
I would try removing the gffutils DB that was previously created by LiftOff and then re-run the tool. The error indicates that the features DB wasn't successfully constructed. 

If your problem persists, I can try looking at your reference annotation.
