### ISSUE TITLE
installation and run issue with Liftoff

### ISSUE THREAD

**Issue by sid5427** [agshumate/Liftoff#24]
Hello,

I installed liftoff as per the manual. However I am having issues running the tool - I get the error message given below- 

```
Python version - Python 3.7.6
minimap2 version - 2.17-r941 (installed via bioconda)
```

liftoff command used -` (liftoff -t ordered_ragtag.scaffold.fasta -r Zea_mays.B73_RefGen_v4.dna.toplevel.fa -g Zea_mays.B73_RefGen_v4.47.gff3 -p 8 -dir int_files_1 -o ordered_ragtag.scaffold.gff) >& log_liftoff_1.txt &`

error message - 
```
Traceback (most recent call last):
  File "/home/ssz74/miniconda3/envs/python3.7/bin/liftoff", line 33, in <module>
    sys.exit(load_entry_point('Liftoff==1.2.2', 'console_scripts', 'liftoff')())
  File "/home/ssz74/miniconda3/envs/python3.7/bin/liftoff", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/ssz74/miniconda3/envs/python3.7/lib/python3.7/site-packages/importlib_metadata-1.7.0-py3.7.egg/importlib_metadata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "/home/ssz74/miniconda3/envs/python3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/home/ssz74/miniconda3/envs/python3.7/lib/python3.7/site-packages/Liftoff-1.2.2-py3.7.egg/liftoff/run_liftoff.py", line 1, in <module>
  File "/home/ssz74/miniconda3/envs/python3.7/lib/python3.7/site-packages/Liftoff-1.2.2-py3.7.egg/liftoff/liftover_types.py", line 1, in <module>
  File "/home/ssz74/miniconda3/envs/python3.7/lib/python3.7/site-packages/Liftoff-1.2.2-py3.7.egg/liftoff/fix_overlapping_features.py", line 1, in <module>
  File "/home/ssz74/miniconda3/envs/python3.7/lib/python3.7/site-packages/Liftoff-1.2.2-py3.7.egg/liftoff/lift_features.py", line 1, in <module>
  File "/home/ssz74/miniconda3/envs/python3.7/lib/python3.7/site-packages/Liftoff-1.2.2-py3.7.egg/liftoff/find_best_mapping.py", line 2, in <module>
ImportError: cannot import name 'new_feature' from 'liftoff' (/home/ssz74/miniconda3/envs/python3.7/lib/python3.7/site-packages/Liftoff-1.2.2-py3.7.egg/liftoff/__init__.py)
```
any help in troubleshooting would be appreciated.

**Comment by agshumate** [comment]
hi there. i just made a change that i believe should fix the problem. please reinstall and let me know if you have the issue again

**Comment by sid5427** [comment]
Hi Alaina,

So I updated to the latest version of liftover, but now I am getting this new error - I believe I am using the correct flags and files to do a standard run of liftover, Minimap2 is directly accessible from the command prompt - so do I still need to explicitly to tell liftover minimap2's path?

```
(liftoff -p 8 \
-dir int_files_1 \
-r Zea_mays.B73_RefGen_v4.dna.toplevel.fa \
-g Zea_mays.B73_RefGen_v4.47.gff3 \
-t ordered_ragtag.scaffold.fasta \
-o ordered_ragtag.scaffold.gff) >& log_liftoff_1.txt &
```

error - 

```
Traceback (most recent call last):
  File "/home/ssz74/miniconda3/envs/python3.7/bin/liftoff", line 33, in <module>
    sys.exit(load_entry_point('Liftoff==1.2.2', 'console_scripts', 'liftoff')())
  File "/home/ssz74/miniconda3/envs/python3.7/lib/python3.7/site-packages/Liftoff-1.2.2-py3.7.egg/liftoff/run_liftoff.py", line 18, in main
TypeError: lift_original_annotation() missing 11 required positional arguments: 'db', 'lifted_feature_list', 'unmapped_features', 'infer_transcripts', 'infer_genes', 'cov_threshold', 'seq_threshold', 'minimap2_path', 'inter_files', 'max_alns', and 'parents_to_lift'
```

Thanks for your quick response and help!

**Comment by agshumate** [comment]
hello again,
so sorry but in my attempt to resolve the previous issue quickly i merged something incorrectly which led to this issue. the latest version is now 1.2.3 so if you install that and run it, it should work for you. your command line looks correct

**Comment by sid5427** [comment]
Awesome - works perfectly now - thanks for the quick resolution!
