### ISSUE TITLE
Can this program liftoff repeats features like transposons between the two genomes of same species？

### ISSUE THREAD

**Issue by bioinformaticspcj** [agshumate/Liftoff#32]
Hi authors,
Thanks for devoloping this very useful tool. I am now tring to use it to liftoff repeats features from one version genome assembly to another of same species but meeting an question. It seems abnormal because it has taken over five days to run and I do know when it will end. Does not this tool deal with  repeats features like transposons ?

Thanks for reading this and I am looking to your valuable advice.

**Comment by agshumate** [comment]
Hi are you using the latest version? (v1.3.0)

**Comment by bioinformaticspcj** [comment]
Hi, I am using v1.1.2. Can v1.3.0 avoid this and deal with repeats features like transposons?

**Comment by agshumate** [comment]
Hi, v1.3.0 will solve the issue of the time it takes to run. However, it has not been tested with repeat features so I cannot guarantee accuracy. If the features have many possible alignments throughout the genome, it may not map them to the correct location. It is certainly worth trying though, but please do upgrade to v1.3.0

**Comment by bioinformaticspcj** [comment]
Hi, I have tried v1.3.0 but still met an error:
"Traceback (most recent call last):
  File "/data/nfs/OriginTools/pcj/python3/miniconda3/bin/liftoff", line 11, in <module>
    load_entry_point('Liftoff==1.3.0', 'console_scripts', 'liftoff')()
  File "/data/nfs/OriginTools/pcj/python3/miniconda3/lib/python3.7/site-packages/Liftoff-1.3.0-py3.7.egg/liftoff/run_liftoff.py", line 18, in main
  File "/data/nfs/OriginTools/pcj/python3/miniconda3/lib/python3.7/site-packages/Liftoff-1.3.0-py3.7.egg/liftoff/liftover_types.py", line 12, in lift_original_annotation
  File "/data/nfs/OriginTools/pcj/python3/miniconda3/lib/python3.7/site-packages/Liftoff-1.3.0-py3.7.egg/liftoff/extract_features.py", line 13, in extract_features_to_lift
  File "/data/nfs/OriginTools/pcj/python3/miniconda3/lib/python3.7/site-packages/Liftoff-1.3.0-py3.7.egg/liftoff/extract_features.py", line 124, in get_gene_sequences
  File "/data/nfs/OriginTools/pcj/python3/miniconda3/lib/python3.7/site-packages/Liftoff-1.3.0-py3.7.egg/liftoff/extract_features.py", line 146, in write_gene_sequences_to_file
IndexError: list index out of range"

the command is as follows:
"/data/nfs/OriginTools/pcj/python3/miniconda3/bin/liftoff -exclude_partial -p 50 -s 0.5 -a 0.5 -t Gshe.genome_chr.fa -r Gshe.genome.fa -g Gshe.repeat.gff -o Gshe.genome_chr.repeat.gff"
 
I do not know why

Thanks for reading and I am looking forward to your help.

**Comment by agshumate** [comment]
Hi,
Does your gff file only contain repeat features? By default Liftoff looks tries to lift over 'gene' features and their children, and this error indicates to me that there are no gene features in your gff. if you want to lift over features besides genes, use -f to provide a file with the names of the features you want to lift over.

**Comment by bioinformaticspcj** [comment]
Hi，
Yes, the gff file only contains repeat features. I have tried v1.3.0 with -f and&nbsp;-exclude_partial -p 80 -s 1 -a 1, it worked but found 1,232,350 repeats were not mapped.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "agshumate/Liftoff"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月10日(星期一) 晚上10:07
收件人:&nbsp;"agshumate/Liftoff"<Liftoff@noreply.github.com&gt;;
抄送:&nbsp;"Monkeyjun"<2532090267@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [agshumate/Liftoff] Can this program liftoff repeats features like transposons between the two genomes of same species？ (#32)





 
Hi,
 Does your gff file only contain repeat features? By default Liftoff looks tries to lift over 'gene' features and their children, and this error indicates to me that there are no gene features in your gff. if you want to lift over features besides genes, use -f to provide a file with the names of the features you want to lift over.

**Comment by agshumate** [comment]
hi,
by setting the -s and -a parameters to 1 and using -exclude_partial, you are only going to map features that are 100% identical to the reference, so even if there is a single nucleotide difference, the repeat will be considered unmapped. If you do indeed only want to count a repeat as 'mapped' if it is a perfect match, and are wondering why so many do not have perfect matches, you can get a better insight to what is going on by looking in the intermediate_files directory at the .sam. alignments from minimap2

**Comment by bioinformaticspcj** [comment]
Hi,
Thanks for giving these valuable advice. I looked through the .sam. alignments from minimap2 and found minimap2 can not map a lot of repeats to the genome. I then tried blastn to align these repeat sequences to the genome and they were all aligned perfectly with 100% indentity.&nbsp;


Thus I think minimap2 is not a good choice for repeats aligning or may be, when you do not want to find new genes in a different version of genome but needing perfect alignments. Could you set a new parameter to allow using different aligners like blat/blast/minimap2 to cope with different data?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "agshumate/Liftoff"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月13日(星期四) 晚上9:47
收件人:&nbsp;"agshumate/Liftoff"<Liftoff@noreply.github.com&gt;;
抄送:&nbsp;"Monkeyjun"<2532090267@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [agshumate/Liftoff] Can this program liftoff repeats features like transposons between the two genomes of same species？ (#32)





 
hi,
 by setting the -s and -a parameters to 1 and using -exclude_partial, you are only going to map features that are 100% identical to the reference, so even if there is a single nucleotide difference, the repeat will be considered unmapped. If you do indeed only want to count a repeat as 'mapped' if it is a perfect match, and are wondering why so many do not have perfect matches, you can get a better insight to what is going on by looking in the intermediate_files directory at the .sam. alignments from minimap2

**Comment by agshumate** [comment]
Hi,
Yes that is something I will add in the near future.
