### ISSUE TITLE
Fail to load features

### ISSUE THREAD

**Issue by joanmarticarreras** [agshumate/Liftoff#40]
Hi @agshumate ,

I've been trying to liftoff some contigs (which contain miRNA) and I realized that the feature 'miRNA' is not recognized by the loader and the run crashes:

```
lifting features
Traceback (most recent call last):
File "/usr/local/bin/liftoff", line 11, in <module> load_entry_point('Liftoff==1.4.2', 'console_scripts', 'liftoff')()
File "/usr/local/lib/python3.6/dist-packages/Liftoff-1.4.2-py3.6.egg/liftoff/run_liftoff.py", line 18, in main
File "/usr/local/lib/python3.6/dist-packages/Liftoff-1.4.2-py3.6.egg/liftoff/liftover_types.py", line 17, in lift_original_annotation
File "/usr/local/lib/python3.6/dist-packages/Liftoff-1.4.2-py3.6.egg/liftoff/liftover_types.py", line 30, in align_and_lift_features
File "/usr/local/lib/python3.6/dist-packages/Liftoff-1.4.2-py3.6.egg/liftoff/lift_features.py", line 20, in lift_all_features
File "/usr/local/lib/python3.6/dist-packages/Liftoff-1.4.2-py3.6.egg/liftoff/lift_features.py", line 96, in lift_single_feature
File "/usr/local/lib/python3.6/dist-packages/Liftoff-1.4.2-py3.6.egg/liftoff/merge_lifted_features.py", line 20, in merge_lifted_features
File "/usr/local/lib/python3.6/dist-packages/Liftoff-1.4.2-py3.6.egg/liftoff/merge_lifted_features.py", line 36, in create_parents
File "/usr/local/lib/python3.6/dist-packages/Liftoff-1.4.2-py3.6.egg/liftoff/merge_lifted_features.py", line 49, in make_new_parent
File "/usr/local/lib/python3.6/dist-packages/Liftoff-1.4.2-py3.6.egg/liftoff/merge_lifted_features.py", line 61, in get_ref_parent
KeyError: 'rna-HHV5wtgp041'
```

After deleting the lines containing miRNA entries, all run good. Might be worth to include other types of entries in future versions (which I am waiting for avidly!).

Best!

POSTEDIT: It might be worth that also transfers repeat tags and alike, as they are currently not being transferred. I don't know if that was well intended or not.

**Comment by agshumate** [comment]
Hi there,
we actually do already have this option! using -f you can provide a txt file with names of features other than genes that you would like to transfer. However, if  liftoff doesnt recognize a feature name it will simply ignore it and it should not crash, so i believe this is a different problem. I have seen this sort of crash before when the feature ID contains a space - the gfftutils library used to parse the gff file for some reason does not like spaces. Does that particular miRNA ID contain a space by chance?

**Comment by joanmarticarreras** [comment]
Hi,

Thanks! Good to know! The miRNA names don't have spaces I think. I used the gff from this NCBI entry (https://www.ncbi.nlm.nih.gov/nuccore/NC_006273), if you want to try to replicate the issue.

Joan

**Comment by agshumate** [comment]
Hi Joan,
Thanks - i was able to reproduce the issue. The problem is due to inconsistent parent/child relationships with the miRNA features in the GFF. There are 3 miRNA's that are children of 'gene' features, but all of the rest do not have a gene feature as their parent. Either structure is okay, as long as its consistent through the file. In the next version of liftoff, i will fix this bug to handle cases like this, but for now a work around is to delete the 'Parent=' field from the 3 miRNAs that have this (rna-HHV5wtgp041, rna-HHV5wtgp041-2, and rna-HHV5wtgp131-2).  Then make sure "miRNA" is included in the file in the -f arg.
