### ISSUE TITLE
Duplicate entry "chr1D" in sam header

### ISSUE THREAD

**Issue by shenweima** [agshumate/Liftoff#45]
**My commond**
`liftoff -g /data2/Fshare/FastaAndIndex/iwgsc_refseqv1.1_genes_2017July06/IWGSC_v1.1_HCandLC_20170706.gff3 -o IWGSC_v1.1_HCandLC_jagger.gff3 -exclude_partial -s 0.9 -flank 0.1 -d 3 -p 8 -chroms chrom.txt -copies -sc 0.9 ../Jagger.genome /data2/Fshare/FastaAndIndex/IWGSC_v1.0_bwa/161010_Chinese_Spring_v1.0_pseudomolecules.fasta`

**The error message**
```
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -o intermediate_files/chr7D_to_chr7D.sam -a --end-bonus 5 --eqx -N 50 -p 0.5 --split-prefix intermediate_files/chr7D_to_chr7D_split -t 1 intermediate_files/chr7D.fa intermediate_files/chr7D_genes.fa
[M::main] Real time: 111.286 sec; CPU: 111.360 sec; Peak RSS: 5.022 GB
[M::worker_pipeline::131.468*1.00] mapped 13386 sequences
[M::worker_pipeline::132.023*1.00] mapped 13386 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -o intermediate_files/chr7B_to_chr7B.sam -a --end-bonus 5 --eqx -N 50 -p 0.5 --split-prefix intermediate_files/chr7B_to_chr7B_split -t 1 intermediate_files/chr7B.fa intermediate_files/chr7B_genes.fa
[M::main] Real time: 132.035 sec; CPU: 132.116 sec; Peak RSS: 5.743 GB
[M::worker_pipeline::196.167*1.00] mapped 12996 sequences
[M::worker_pipeline::196.850*1.00] mapped 12996 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -o intermediate_files/chr6B_to_chr6B.sam -a --end-bonus 5 --eqx -N 50 -p 0.5 --split-prefix intermediate_files/chr6B_to_chr6B_split -t 1 intermediate_files/chr6B.fa intermediate_files/chr6B_genes.fa
[M::main] Real time: 196.868 sec; CPU: 196.949 sec; Peak RSS: 5.548 GB
[W::sam_hdr_create] Duplicated sequence 'chr1D'
[E::sam_hrecs_update_hashes] Duplicate entry "chr1D" in sam header
[E::sam_parse1] failed to parse header
[W::sam_read1] Parse error at line 4
Traceback (most recent call last):
  File "/usr/bin/liftoff", line 11, in <module>
    load_entry_point('Liftoff==1.5.0', 'console_scripts', 'liftoff')()
  File "/usr/lib/python3.6/site-packages/Liftoff-1.5.0-py3.6.egg/liftoff/run_liftoff.py", line 19, in main
  File "/usr/lib/python3.6/site-packages/Liftoff-1.5.0-py3.6.egg/liftoff/liftover_types.py", line 17, in lift_original_annotation
  File "/usr/lib/python3.6/site-packages/Liftoff-1.5.0-py3.6.egg/liftoff/liftover_types.py", line 26, in align_and_lift_features
  File "/usr/lib/python3.6/site-packages/Liftoff-1.5.0-py3.6.egg/liftoff/align_features.py", line 25, in align_features_to_target
  File "/usr/lib/python3.6/site-packages/Liftoff-1.5.0-py3.6.egg/liftoff/align_features.py", line 115, in parse_all_sam_files
  File "/usr/lib/python3.6/site-packages/Liftoff-1.5.0-py3.6.egg/liftoff/align_features.py", line 127, in parse_alignment
  File "pysam/libcalignmentfile.pyx", line 2187, in pysam.libcalignmentfile.IteratorRowAll.__next__
OSError: truncated file
```
**However , when I  run this commond alone, it works**.
```
[masw@genomics2 raw]$ minimap2 -o intermediate_files/chr1D_to_chr1D.sam -a --end-bonus 5 --eqx -N 50 -p 0.5 --split-prefix intermediate_files/chr6B_to_chr6B_split -t 1 intermediate_files/chr1D.fa intermediate_files/chr1D_genes.fa
[M::mm_idx_gen::16.541*1.00] collected minimizers
[M::mm_idx_gen::26.426*1.00] sorted minimizers
[M::main::26.426*1.00] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::26.948*1.00] mid_occ = 947
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::27.181*1.00] distinct minimizers: 24238624 (69.11% are singletons); average occurrences: 3.743; average spacing: 5.439
[M::worker_pipeline::81.849*1.00] mapped 10465 sequences
[M::worker_pipeline::82.343*1.00] mapped 10465 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -o intermediate_files/chr1D_to_chr1D.sam -a --end-bonus 5 --eqx -N 50 -p 0.5 --split-prefix intermediate_files/chr6B_to_chr6B_split -t 1 intermediate_files/chr1D.fa intermediate_files/chr1D_genes.fa
[M::main] Real time: 82.352 sec; CPU: 82.321 sec; Peak RSS: 3.892 GB
```
**I have test it on other wheat genomes,but the same error was found.**
`liftoff -g Jagger.release.gff -o IWGSC_v1.1_HCandLC_jagger.gff3 -exclude_partial -s 0.9 -flank 0.1 -d 3 -p 8 -chroms chrom.txt -copies -sc 0.9 ../SY_Mattis.genome ../Jagger.genome`

**Acturally, I found chr1D had finished before**.
```
M::mm_idx_gen::29.057*1.00] sorted minimizers
[M::main::29.057*1.00] loaded/built the index for 1 target sequence(s)
[M::mm_idx_gen::29.258*1.00] collected minimizers
[M::mm_mapopt_update::29.548*1.00] mid_occ = 942
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::29.849*1.00] distinct minimizers: 24057549 (69.16% are singletons); average occurrences: 3.755; average spacing: 5.383
[M::mm_idx_gen::32.154*1.00] collected minimizers
[M::mm_idx_gen::32.825*1.00] sorted minimizers
[M::main::32.825*1.00] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::33.827*1.00] mid_occ = 1114
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::34.383*1.00] distinct minimizers: 27324975 (66.54% are singletons); average occurrences: 4.091; average spacing: 5.373
[M::mm_idx_gen::36.071*1.00] sorted minimizers
[M::main::36.071*1.00] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::37.054*1.00] mid_occ = 1009
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::37.666*1.00] distinct minimizers: 31975961 (64.91% are singletons); average occurrences: 3.981; average spacing: 5.382
[M::mm_idx_gen::38.344*1.00] sorted minimizers
[M::main::38.344*1.00] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::39.337*1.00] mid_occ = 1049
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::39.785*1.00] distinct minimizers: 30322496 (66.56% are singletons); average occurrences: 4.015; average spacing: 5.383
[M::mm_idx_gen::41.116*1.00] sorted minimizers
[M::main::41.116*1.00] loaded/built the index for 1 target sequence(s)
[M::mm_idx_gen::41.554*1.00] sorted minimizers
[M::main::41.554*1.00] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::42.061*1.00] mid_occ = 1049
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_mapopt_update::42.581*1.00] mid_occ = 1255
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::42.599*1.00] distinct minimizers: 36447326 (63.76% are singletons); average occurrences: 4.080; average spacing: 5.379
[M::mm_idx_stat::43.116*1.00] distinct minimizers: 33718823 (64.03% are singletons); average occurrences: 4.383; average spacing: 5.374
[M::mm_idx_gen::43.810*1.00] sorted minimizers
[M::main::43.811*1.00] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::44.841*1.00] mid_occ = 1227
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::45.328*1.00] distinct minimizers: 32140942 (64.74% are singletons); average occurrences: 4.342; average spacing: 5.372
[M::mm_idx_gen::47.607*1.00] sorted minimizers
[M::main::47.607*1.00] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::48.735*1.00] mid_occ = 1068
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::49.552*1.00] distinct minimizers: 37315242 (63.01% are singletons); average occurrences: 4.169; average spacing: 5.387
[M::worker_pipeline::54.399*1.00] mapped 4816 sequences
[M::worker_pipeline::54.671*1.00] mapped 4816 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -o intermediate_files/chr1D_to_chr1D.sam -a --end-bonus 5 --eqx -N 50 -p 0.5 --split-prefix intermediate_files/chr1D_to_chr1D_split -t 1 intermediate_files/chr1D.fa intermediate_files/chr1D_genes.fa
[M::main] Real time: 54.673 sec; CPU: 54.695 sec; Peak RSS: 3.877 GB
[M::worker_pipeline::63.552*1.00] mapped 4646 sequences
[M::worker_pipeline::63.914*1.00] mapped 4646 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -o intermediate_files/chr1A_to_chr1A.sam -a --end-bonus 5 --eqx -N 50 -p 0.5 --split-prefix intermediate_files/chr1A_to_chr1A_split -t 1 intermediate_files/chr1A.fa intermediate_files/chr1A_genes.fa
[M::main] Real time: 63.916 sec; CPU: 63.943 sec; Peak RSS: 4.810 GB
[M::worker_pipeline::65.541*1.00] mapped 5058 sequences
[M::worker_pipeline::65.890*1.00] mapped 5058 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -o intermediate_files/chr1B_to_chr1B.sam -a --end-bonus 5 --eqx -N 50 -p 0.5 --split-prefix intermediate_files/chr1B_to_chr1B_split -t 1 intermediate_files/chr1B.fa intermediate_files/chr1B_genes.fa
[M::main] Real time: 65.893 sec; CPU: 65.915 sec; Peak RSS: 5.343 GB
[M::worker_pipeline::68.012*1.00] mapped 6385 sequences
[M::worker_pipeline::68.420*1.00] mapped 6385 sequences
```

**Comment by agshumate** [comment]
Hi there,
If you upgrade your minimap2 version to  2.17-r974 or later, you should not have this issue anymore.

**Comment by Raanaroohanitaziani** [comment]
> Hi there, If you upgrade your minimap2 version to 2.17-r974 or later, you should not have this issue anymore. The error is coming from parsing the sam files after minimap2 finishes, which is why the minimap2 command by itself runs fine. With the later version of minimap2, duplicate headers are not produced with --split-prefix so you should not get this parsing error.

hi. I am using the version 2.22-r1101, but I get the same parse error in pysam : "Duplicate entry "gi|169302992|ref|NC_010403.1|" in sam header". I searched in the manual but i did not find any solution yet. I hope someone can help me with this.
