### ISSUE TITLE
interlap error when using -copies option

### ISSUE THREAD

**Issue by seanrj-conagen** [agshumate/Liftoff#56]
I get an error when using the -copies option (when I leave that option off, it seems to run fine).
Here is my command line log:
```
$ liftoff -g ref.gff -o new.gff -copies new.fasta ref.fasta 
extracting features
2020-12-26 12:05:32,345 - INFO - Populating features
2020-12-26 12:05:35,173 - INFO - Populating features table and first-order relations: 109592 features
2020-12-26 12:05:35,173 - INFO - Updating relations
2020-12-26 12:05:35,536 - INFO - Creating relations(parent) index
2020-12-26 12:05:35,537 - INFO - Creating relations(child) index
2020-12-26 12:05:35,537 - INFO - Creating features(featuretype) index
2020-12-26 12:05:35,572 - INFO - Creating features (seqid, start, end) index
2020-12-26 12:05:35,606 - INFO - Creating features (seqid, start, end, strand) index
2020-12-26 12:05:35,643 - INFO - Running ANALYZE features
aligning features
[M::main::0.387*1.00] loaded/built the index for 13 target sequence(s)
[M::mm_mapopt_update::0.497*1.00] mid_occ = 9
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 13
[M::mm_idx_stat::0.577*1.00] distinct minimizers: 7514366 (94.48% are singletons); average occurrences: 1.068; average spacing: 5.351
[M::worker_pipeline::4.959*1.00] mapped 11224 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -o intermediate_files/reference_all_to_target_all.sam -a --end-bonus 5 --eqx -N 50 -p 0.5 -t 1 new.fasta.mmi intermediate_files/reference_all_genes.fa
[M::main] Real time: 4.975 sec; CPU: 4.968 sec; Peak RSS: 0.313 GB
lifting features
mapping gene copies
aligning features
[M::main::0.380*1.00] loaded/built the index for 13 target sequence(s)
[M::mm_mapopt_update::0.491*1.00] mid_occ = 9
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 13
[M::mm_idx_stat::0.573*1.00] distinct minimizers: 7514366 (94.48% are singletons); average occurrences: 1.068; average spacing: 5.351
[M::worker_pipeline::4.856*1.00] mapped 11224 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -o intermediate_files/reference_all_to_target_all.sam -a --end-bonus 5 --eqx -N 50 -p 0.5 -t 1 new.fasta.mmi intermediate_files/reference_all_genes.fa
[M::main] Real time: 4.870 sec; CPU: 4.869 sec; Peak RSS: 0.313 GB
lifting features
Traceback (most recent call last):
  File "/opt/ccc/packages/miniconda3/envs/liftoff/bin/liftoff", line 10, in <module>
    sys.exit(main())
  File "/opt/ccc/packages/miniconda3/envs/liftoff/lib/python3.8/site-packages/liftoff/run_liftoff.py", line 25, in main
    map_extra_copies(args, lifted_feature_list, feature_hierarchy, feature_db, ref_parent_order)
  File "/opt/ccc/packages/miniconda3/envs/liftoff/lib/python3.8/site-packages/liftoff/run_liftoff.py", line 202, in map_extra_copies
    liftover_types.map_extra_copies(ref_chroms, target_chroms, lifted_feature_list, feature_hierarchy, feature_db,                                                                                  
  File "/opt/ccc/packages/miniconda3/envs/liftoff/lib/python3.8/site-packages/liftoff/liftover_types.py", line 95, in map_extra_copies                                                              
    align_and_lift_features(ref_chroms, target_chroms, args, feature_hierarchy, liftover_type, unmapped_features,                                                                                   
  File "/opt/ccc/packages/miniconda3/envs/liftoff/lib/python3.8/site-packages/liftoff/liftover_types.py", line 33, in align_and_lift_features                                                       
    fix_overlapping_features.fix_incorrectly_overlapping_features(lifted_features_list, lifted_features_list,                                                                                       
  File "/opt/ccc/packages/miniconda3/envs/liftoff/lib/python3.8/site-packages/liftoff/fix_overlapping_features.py", line 11, in fix_incorrectly_overlapping_features                                
    features_to_remap, feature_locations = check_homologues(all_lifted_features, features_to_check,                                                                                                 
  File "/opt/ccc/packages/miniconda3/envs/liftoff/lib/python3.8/site-packages/liftoff/fix_overlapping_features.py", line 24, in check_homologues                                                    
    feature_locations = build_interval_list(all_feature_list)                                                                                                                                       
  File "/opt/ccc/packages/miniconda3/envs/liftoff/lib/python3.8/site-packages/liftoff/fix_overlapping_features.py", line 42, in build_interval_list                                                 
    inter.update(feature_coords)
  File "/opt/ccc/packages/miniconda3/envs/liftoff/lib/python3.8/site-packages/interlap.py", line 142, in add
    iset.sort()
TypeError: '<' not supported between instances of 'new_feature' and 'new_feature'

```

**Comment by agshumate** [comment]
Hi Sean,
I apologize for the delayed response. This was an issue related to the -copies option. I created a new release v1.5.2 where this issue have been fixed. 
Best,
Alaina
