### ISSUE TITLE
AttributeError: 'Fasta' object has no attribute 'values'

### ISSUE THREAD

**Issue by reachsagaya** [agshumate/Liftoff#64]
Iam running the following:
liftoff -g  GCF_002870075.1_Lsat_Salinas_v7_genomic.gff -p 14 -o Lsatv10_v7.gff Genome_v10.01.fasta GCF_002870075.1_Lsat_Salinas_v7_genomic.fna
Here is the error I get:
`2021-03-03 21:57:28,408 - INFO - Running ANALYZE features
aligning features
Traceback (most recent call last):
  File "/share/rwm/SS/Packages/anaconda3/envs/liftoff_env/bin/liftoff", line 10, in <module>sys.exit(main())
  File "/share/rwm/SS/Packages/anaconda3/envs/liftoff_env/lib/python3.6/site-packages/liftoff/run_liftoff.py", line 19, in main parent_features_to_lift)
  File "/share/rwm/SS/Packages/anaconda3/envs/liftoff_env/lib/python3.6/site-packages/liftoff/liftover_types.py", line 17, in lift_original_annotation
    args.overlap)
  File "/share/rwm/SS/Packages/anaconda3/envs/liftoff_env/lib/python3.6/site-packages/liftoff/liftover_types.py", line 26, in align_and_lift_features
    liftover_type, unmapped_features)
  File "/share/rwm/SS/Packages/anaconda3/envs/liftoff_env/lib/python3.6/site-packages/liftoff/align_features.py", line 15, in align_features_to_target
    genome_size = get_genome_size(target_fasta_dict)
  File "/share/rwm/SS/Packages/anaconda3/envs/liftoff_env/lib/python3.6/site-packages/liftoff/align_features.py", line 40, in get_genome_size
    for value in target_fasta_dict.values():
AttributeError: 'Fasta' object has no attribute 'values'
`

**Comment by agshumate** [comment]
Hi,
Which version of liftoff are you using? And can you check your working directory to see if there was an index made for Genome_v10.01.fasta?

**Comment by reachsagaya** [comment]
Thanks for your quick response.
I downloaded the latest version of liftoff v1.5.2, but liftoff -V still says v1.5.1.
In the working directory, it does create the index file. The run crashes at the Running ANALYZE features stage.

`
2021-03-03 21:52:21,394 - INFO - Populating features
2021-03-03 21:56:36,268 - INFO - Populating features table and first-order relations: 714960 features
2021-03-03 21:56:36,269 - INFO - Updating relations
2021-03-03 21:57:13,001 - INFO - Creating relations(parent) index
2021-03-03 21:57:15,865 - INFO - Creating relations(child) index
2021-03-03 21:57:20,323 - INFO - Creating features(featuretype) index
2021-03-03 21:57:22,280 - INFO - Creating features (seqid, start, end) index
2021-03-03 21:57:25,334 - INFO - Creating features (seqid, start, end, strand) index
2021-03-03 21:57:28,408 - INFO - Running ANALYZE features
`

**Comment by agshumate** [comment]
Does the index file look as expected with the correct number of chromosomes/contigs?

**Comment by reachsagaya** [comment]
Here is how it looks
Lsat_1_v10_chr1	247928466	17	60	61
Lsat_1_v10_chr2	234982731	252060642	60	61
Lsat_1_v10_chr3	323094788	490959769	60	61
Lsat_1_v10_chr4	406360200	819439488	60	61
Lsat_1_v10_chr5	368878906	1232572375	60	61
Lsat_1_v10_chr6	206250288	1607599280	60	61
Lsat_1_v10_chr7	208571662	1817287090	60	61
Lsat_1_v10_chr8	340764772	2029334964	60	61
Lsat_1_v10_chr9	228713657	2375779166	60	61
Lsat_1_v10_Unsc_0_	10433435	2608304738	60	61

**Comment by agshumate** [comment]
okay that looks correct. are you working in a conda environment and if so, which version of pyfaidx is installed?

**Comment by reachsagaya** [comment]
Iam using the conda environment and the pyfaidx version is 0.5.9.5.

**Comment by agshumate** [comment]
is there any chance the Genome_v10.01.fasta is available for me to test? If not, my first suggestion is to delete the .fai files and anything in the intermediate_files directory and re-run.

**Comment by reachsagaya** [comment]
Sure I can share the Genome_v10.01.fasta file with you. Here is my email id ssagayaradj@ucdavis.edu, could you share with me how would you like to receive the fasta file?  

Also I will give it another try.

Thanks and you may close this issue.
