### ISSUE TITLE
Failed to run Liftoff

### ISSUE THREAD

**Issue by harazono** [agshumate/Liftoff#71]
Hello.

I tried to execute `liftoff -h` but I faced to this error.
```
🍵~$ liftoff 
/usr/local/lib/python3.9/site-packages/Liftoff-1.6.1-py3.9.egg/liftoff/run_liftoff.py:43: SyntaxWarning: "is not" with a literal. Did you mean "!="?
/usr/local/lib/python3.9/site-packages/Liftoff-1.6.1-py3.9.egg/liftoff/run_liftoff.py:43: SyntaxWarning: "is not" with a literal. Did you mean "!="?
Python(4683,0x1185a2dc0) malloc: can't allocate region
:*** mach_vm_map(size=18446744071778885632, flags: 100) failed (error code=3)
Python(4683,0x1185a2dc0) malloc: *** set a breakpoint in malloc_error_break to debug
init_dgelsd failed init
Traceback (most recent call last):
  File "/usr/local/bin/liftoff", line 33, in <module>
    sys.exit(load_entry_point('Liftoff==1.6.1', 'console_scripts', 'liftoff')())
  File "/usr/local/bin/liftoff", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.9/site-packages/Liftoff-1.6.1-py3.9.egg/liftoff/run_liftoff.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.9/site-packages/Liftoff-1.6.1-py3.9.egg/liftoff/write_new_gff.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.9/site-packages/Liftoff-1.6.1-py3.9.egg/liftoff/liftoff_utils.py", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/numpy/__init__.py", line 286, in <module>
    raise RuntimeError(msg)
RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
RankWarning: Polyfit may be poorly conditioned

🍵~$ 
```
I'm not sure why python tried to malloc such a huge memory.
I'm using macOS Catalina v10.15.7 with intel core i7.
Are there something I missed?

Thanks.

**Comment by harazono** [comment]
I installed `liftoff` by running `python3 setup.py install`.

**Comment by harazono** [comment]
Same issue was occurred during running other python scripts in my environment.
This error is not specific for `liftoff`.
Sorry for bothering you.
