### ISSUE TITLE
question: CDS-only source GFF?

### ISSUE THREAD

**Issue by spock** [agshumate/Liftoff#74]
Hello,

thank you for a wonderful tool! 🙂 

I'm trying to copy annotations from a weird, CDS-only .GFF file, using `liftoff` v1.6.1.

This is the command I'm using:
```
liftoff -g source.gff -u sample_unmapped_features.txt -infer_genes -infer_transcripts \
  -f TYPES -dir sample_tmp -copies -p 4 sample.fasta source.fasta | tee sample.gff
```
(`TYPES` is a text file with 'CDS' line in it.)

I'm getting an exception, which suggests that `lifotff` is looking for `Parent` tags on the CDS:
```
aligning features
lifting features
mapping gene copies
[M::main::0.255*1.00] loaded/built the index for 384 target sequence(s)
[M::mm_mapopt_update::0.324*1.00] mid_occ = 118
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 384
[M::mm_idx_stat::0.373*1.00] distinct minimizers: 5373805 (91.65% are singletons); average occurrences: 1.312; average spacing: 5.341
[M::worker_pipeline::108.609*2.32] mapped 8539 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -o sample_tmp/reference_all_to_target_all.sam -a --end-bonus 5 --eqx -N 50 -p 0.5 -t 4 sample.fasta.mmi sample_tmp/reference_all_genes.fa
[M::main] Real time: 108.626 sec; CPU: 251.706 sec; Peak RSS: 2.007 GB
Traceback (most recent call last):
  File ".local/bin/liftoff", line 8, in <module>
    sys.exit(main())
  File ".local/lib/python3.7/site-packages/liftoff/run_liftoff.py", line 10, in main
    run_all_liftoff_steps(args)
  File ".local/lib/python3.7/site-packages/liftoff/run_liftoff.py", line 35, in run_all_liftoff_steps
    check_cds(lifted_feature_list, feature_hierarchy, args)
  File ".local/lib/python3.7/site-packages/liftoff/run_liftoff.py", line 275, in check_cds
    target_faidx, feature_list[target_feature])
  File ".local/lib/python3.7/site-packages/liftoff/polish.py", line 39, in find_and_check_cds
    target_sub_features, feature_list)
  File ".local/lib/python3.7/site-packages/liftoff/polish.py", line 54, in count_good_cds
    grouped_cds = group_cds_by_tran(cds_features)
  File ".local/lib/python3.7/site-packages/liftoff/polish.py", line 121, in group_cds_by_tran
    groups[cds.attributes["Parent"][0]].append(cds)
KeyError: 'Parent'
aligning features
lifting features
```

I have also tried not specifying `-f TYPES` (or writing `gene` in the file instead of `CDS`), but that results in:
```
GFF does not contain any gene features. Use -f to provide a list of other feature types to lift over.
```

Is there a way to make this work with `liftoff`, without adding some wrapper `gene` features to CDS?

Currently also trying the TYPES file with all of: gene, transcript, CDS - let's see if this works.

Thanks!

**Comment by spock** [comment]
it looks like I was able to  mutilate `polish.py` enough for this to work 😁 
(obviously ugly/hacky, and hard-coding the ID that I'd want to use - thus no pull request)

```
diff --git a/liftoff/polish.py b/liftoff/polish.py
index b13d21a..f07936c 100644
--- a/liftoff/polish.py
+++ b/liftoff/polish.py
@@ -55,8 +55,9 @@ def count_good_cds(cds_features, ref_faidx, target_faidx, ref_children, target_s
     good_cds_count = 0
     for cds_group in grouped_cds:
         cds_seq = get_seq(cds_group, target_faidx)
-        transcript = [feature for feature in target_sub_features if feature.id == cds_group[0].attributes["Parent"][
-            0]][0]
+        # FIXME
+        # transcript = [feature for feature in target_sub_features if feature.id == cds_group[0].attributes["Parent"][0]][0]
+        transcript = [ feature for feature in target_sub_features if feature.id == cds_group[0].attributes["ID"][0] ][0]
         with warnings.catch_warnings():
             warnings.simplefilter('ignore')
             protein = cds_seq.translate()
@@ -118,7 +119,9 @@ def adjust_cds_coords(cds_features, longest_ORF_coords, feature_list):
 def group_cds_by_tran(cds_features):
     groups = defaultdict(list)
     for cds in cds_features:
-        groups[cds.attributes["Parent"][0]].append(cds)
+        # FIXME
+        # groups[cds.attributes["Parent"][0]].append(cds)
+        groups[cds.attributes["protein_id"][0]].append(cds)
     return groups.values()
 
 
@@ -150,10 +153,11 @@ def inframe_stop(protein):
 
 
 def matches_ref(cds_group, ref_fa, ref_children, target_protein):
-    tran = cds_group[0].attributes["Parent"]
-    ref_cds_group= [ref_cds for ref_cds in ref_children if ref_cds.featuretype=="CDS" and ref_cds.attributes[
-        "Parent"] ==
-                    tran]
+    # FIXME
+    # tran = cds_group[0].attributes["Parent"]
+    tran = cds_group[0].attributes["ID"]
+    # ref_cds_group= [ref_cds for ref_cds in ref_children if ref_cds.featuretype=="CDS" and ref_cds.attributes["Parent"] == tran]
+    ref_cds_group= [ref_cds for ref_cds in ref_children if ref_cds.featuretype=="CDS" and ref_cds.attributes["ID"] == tran]
     ref_cds_seq = get_seq(ref_cds_group, ref_fa)
     with warnings.catch_warnings():
         warnings.simplefilter('ignore')
```

**Comment by agshumate** [comment]
Hi there,
I'm glad you found a solution. My suggestion was going to be to use gffread (https://github.com/gpertea/gffread) to add the parent mRNA. simply running `gffread filename.gff` should add a parent mRNA. You could then filter these out from you output if you don't want them

**Comment by spock** [comment]
great suggestion, much cleaner than what I've done - thank you, @agshumate!
