### ISSUE TITLE
Duplicate contig names in SAM header cause crash

### ISSUE THREAD

**Issue by ascheben** [agshumate/Liftoff#8]
Thanks for writing this useful tool. I encountered an issue with the SAM file of mapped gene sequences that crashed the program. I was able to replicate the issue using public data of two mammalian genomes.

```
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/002/940/915/GCF_002940915.1_ASM294091v2/GCF_002940915.1_ASM294091v2_genomic.fna.gz
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/002/940/915/GCF_002940915.1_ASM294091v2/GCF_002940915.1_ASM294091v2_genomic.gff.gz
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/001/466/805/GCF_001466805.2_Raegyp2.0/GCF_001466805.2_Raegyp2.0_genomic.fna.gz
gzip -d *gz

python liftoff.py -dir testdir -p 1 -r GCF_002940915.1_ASM294091v2_genomic.fna -g GCF_002940915.1_ASM294091v2_genomic.gff -t GCA_001466805.2_Raegyp2.0_genomic.fna -o test.gff -m /path/to/minimap2

```

After the feature database is constructed, the following error occurs. I have omitted some of the 'Duplicated sequence warning' but they occur once for every contig in the target FASTA.

```
extracting features
aligning features
[W::sam_hdr_create] Duplicated sequence 'LOCP02000998.1'
[W::sam_hdr_create] Duplicated sequence 'LOCP02000999.1'
[E::sam_hrecs_update_hashes] Duplicate entry "LOCP02000001.1" in sam header
[E::sam_parse1] failed to parse header
[W::sam_read1] Parse error at line 4980
Traceback (most recent call last):
  File "liftoff.py", line 121, in <module>
    main()
  File "liftoff.py", line 74, in main
    unmapped_features, infer_transcripts, infer_genes, cov_threshold, seq_threshold, minimap2_path, inter_files)
  File "../liftover_types.py", line 17, in lift_original_annotation
    unmapped_features, reference_fasta, minimap2_path, inter_files, True)
  File "../align_features.py", line 29, in align_features_to_target
    aligned_segments = parse_alignment(file, parent_dict, children_dict, unmapped_features, search_type)
  File "../align_features.py", line 84, in parse_alignment
    for ref_seq in sam_file_iter:
  File "pysam/libcalignmentfile.pyx", line 2187, in pysam.libcalignmentfile.IteratorRowAll.__next__
OSError: truncated file
```

**Comment by agshumate** [comment]
Hi there, please try updating your Minimap2 to the latest version (2.17-r974-dirty) and let me know if the problems persists

**Comment by ascheben** [comment]
Thanks this resolves the issue. I was using 2.17-r941
