### ISSUE TITLE
Unable to install liftoff

### ISSUE THREAD

**Issue by margaretwoodhouse** [agshumate/Liftoff#81]
Hi, there:

I'm trying to re-install the latest version of liftoff using conda. However, even though I've removed the old liftoff environment, I am getting this error when installing the new version of liftoff:

```
UnsatisfiableError: The following specifications were found to be incompatible with each other

Package python conflicts for:
liftoff -> python[version='>=3']
Package ujson conflicts for:
liftoff -> ujson
Package numpy conflicts for:
liftoff -> numpy[version='>=1.19.0']
Package networkx conflicts for:
liftoff -> networkx[version='>=2.4']
Package parasail-python conflicts for:
liftoff -> parasail-python[version='>=1.2.1']
Package pysam conflicts for:
liftoff -> pysam[version='>=0.16.0.1']
Package minimap2 conflicts for:
liftoff -> minimap2
Package pyfaidx conflicts for:
liftoff -> pyfaidx[version='>=0.5.8']
Package gffutils conflicts for:
liftoff -> gffutils[version='>=0.10.1']
Package biopython conflicts for:
liftoff -> biopython[version='>=1.76']
Package interlap conflicts for:
liftoff -> interlap[version='>=0.2.6']
```

I have tried 

```
conda install -c bioconda liftoff

conda install -n liftoff -c bioconda liftoff

conda create -n liftoff -c bioconda liftoff python=3.8

conda create -n liftoff -c bioconda liftoff python=3.7
```

and all of them are giving me this error. I'm also having issues installing through pip and installing using setup.py. I didn't have these issues before so I'm not sure what's going on. Note that I'm on an HPC, and it seems as though it's trying to install into root instead of my local environment. Thanks so much.

**Comment by agshumate** [comment]
try running `conda create -n liftoff -c bioconda -c conda-forge liftoff`

this is the same issue as #73, #52, and #48 . this error indicates that you have not set up the conda channels/dependencies as specified here https://bioconda.github.io/user/install.html#set-up-channels

**Comment by margaretwoodhouse** [comment]
I tried 

`conda create -n liftoff -c bioconda -c conda-forge liftoff`

and it was able to install. However, when I run

`liftoff -h`

I get this error now:

```
Traceback (most recent call last):
  File "/home/.conda/envs/liftoff/bin/liftoff", line 6, in <module>
    from liftoff.run_liftoff import main
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/.local/lib/python3.6/site-packages/Liftoff-1.6.1-py3.6.egg/liftoff/run_liftoff.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/.local/lib/python3.6/site-packages/Liftoff-1.6.1-py3.6.egg/liftoff/polish.py", line 5, in <module>
  File "/home/.local/lib/python3.6/site-packages/parasail-1.2.1-py3.6.egg/parasail/__init__.py", line 70, in <module>
    raise Exception("failed to locate and open '{}'".format(_libname))
Exception: failed to locate and open 'libparasail.so'
```

I was also getting this error after I'd installed liftoff using setup.py.

**Comment by agshumate** [comment]
have you activated the new conda environment after re-installing? if so you should see a * next to liftoff if you run `conda env list`

**Comment by margaretwoodhouse** [comment]
It was an issue with the existing python module in my HPC; when I installed with pip invoking the right module on the HPC, it worked. Thanks so much.
