### ISSUE TITLE
polishing annotation, index out of range

### ISSUE THREAD

**Issue by weihongqi** [agshumate/Liftoff#82]
Dear Alaina,

While running the most recent release of liftoff, the -polish switch triggered "index out of range" error with my dataset:
[M::main] Real time: 1114.351 sec; CPU: 1114.308 sec; Peak RSS: 4.365 GB
aligning features
lifting features
polishing annotations
Traceback (most recent call last):
  File "/usr/local/ngseq/miniconda3/envs/liftoff/bin/liftoff", line 10, in <module>
    sys.exit(main())
  File "/usr/local/ngseq/miniconda3/envs/liftoff/lib/python3.6/site-packages/liftoff/run_liftoff.py", line 10, in main
    run_all_liftoff_steps(args)
  File "/usr/local/ngseq/miniconda3/envs/liftoff/lib/python3.6/site-packages/liftoff/run_liftoff.py", line 42, in run_all_liftoff_steps
    unmapped_features, feature_db, ref_parent_order)
  File "/usr/local/ngseq/miniconda3/envs/liftoff/lib/python3.6/site-packages/liftoff/run_liftoff.py", line 244, in find_and_polish_broken_cds
    aligned_segments_new[target_feature] = list(aligned_segments.values())[0]
IndexError: list index out of range

it works well without the annotation polishing step, with and withour looking for the extra copies (-sc 0.95 to 0.98), with and without excluding the partially mapped features. 

The input reference gff has only protein coding genes with the following features:
CDS
five_prime_UTR
gene
mRNA
three_prime_UTR

I would like to investigate how many genes can be transfer in frame, how many are likely becoming pseudogenes. I wonder what were the cause for this error during annotation polishing, which occurred even only with the best match per gene. 

Many thanks in advance.

Kind regards,

Weihong

**Comment by agshumate** [comment]
Hi Weihong,
Is the data you are working with publicly available or are you able to share it in some way with me so i can test it out?
Best,
Alaina

**Comment by weihongqi** [comment]
Dear Alaina,
Thanks so much for your quick response. 
The dataset is still private. But I emailed them to your gmail account. Looking forward to hearing about your findings and suggestions.
Kind regards,
Weihong

**Comment by agshumate** [comment]
To provide an update for others who may encounter this issue: this issue was because the reference GFF did not have any 'exon' features (only CDS). Commit 169daf602b7dbc13ae1cac24bb31d1384353223d on the master branch has resolved this particular issue.

**Comment by Symeriz** [comment]
Dear Alaina,

Thank you for the amazing work and replying to comments. I am a newbie in pretty much everything 'bioinformatic' and your replies have been very helpful in getting me this far, but I am stuck now! 

I am trying to lift annotations from one assembly to another (same organism different strains), but the -polish switch triggers "index out of range" error. I am using latest version (v1.6.3).-

2022-12-20 17:02:12,736 - INFO - Populating features
Populating features table and first-order relations: 0 features
Populating features table and first-order relations: 1000 features
Populating features table and first-order relations: 2000 features
Populating features table and first-order relations: 3000 features
Populating features table and first-order relations: 4000 features
2022-12-20 17:02:12,984 - INFO - Populating features table and first-order relations: 4417 features
2022-12-20 17:02:12,984 - INFO - Updating relations
2022-12-20 17:02:13,009 - INFO - Creating relations(parent) index
2022-12-20 17:02:13,009 - INFO - Creating relations(child) index
2022-12-20 17:02:13,009 - INFO - Creating features(featuretype) index
2022-12-20 17:02:13,011 - INFO - Creating features (seqid, start, end) index
2022-12-20 17:02:13,012 - INFO - Creating features (seqid, start, end, strand) index
2022-12-20 17:02:13,014 - INFO - Running ANALYZE features
extracting features
[M::main::0.023*0.69] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.026*0.61] mid_occ = 10
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.028*0.56] distinct minimizers: 192463 (99.17% are singletons); average occurrences: 1.009; average spacing: 5.350; total length: 1038842
[M::worker_pipeline::0.415*0.72] mapped 3273 sequences
[M::main] Version: 2.24-r1122
[M::main] CMD: minimap2 -o intermediate_files/reference_all_to_target_all.sam -a --end-bonus 5 --eqx -N 50 -p 0.5 -t 1 sequences/genomes/cTrachomatis/L2434Bu.fasta.mmi intermediate_files/reference_all_genes.fa
[M::main] Real time: 0.418 sec; CPU: 0.297 sec; Peak RSS: 0.012 GB
aligning features
lifting features
polishing annotations
Traceback (most recent call last):
  File "/home/meraj/anaconda3/envs/analysis/bin/liftoff", line 10, in <module>
    sys.exit(main())
  File "/home/meraj/anaconda3/envs/analysis/lib/python3.10/site-packages/liftoff/run_liftoff.py", line 12, in main
    run_all_liftoff_steps(args)
  File "/home/meraj/anaconda3/envs/analysis/lib/python3.10/site-packages/liftoff/run_liftoff.py", line 40, in run_all_liftoff_steps
    check_cds(lifted_feature_list, feature_hierarchy, args)
  File "/home/meraj/anaconda3/envs/analysis/lib/python3.10/site-packages/liftoff/run_liftoff.py", line 276, in check_cds
    polish.find_and_check_cds(target_sub_features, ref_sub_features, ref_faidx,
  File "/home/meraj/anaconda3/envs/analysis/lib/python3.10/site-packages/liftoff/polish.py", line 38, in find_and_check_cds
    total_cds, num_good_cds = count_good_cds(cds_features, ref_faidx, target_faidx, ref_sub_features,
  File "/home/meraj/anaconda3/envs/analysis/lib/python3.10/site-packages/liftoff/polish.py", line 63, in count_good_cds
    if matches_ref(cds_group, ref_faidx, ref_children, protein):
  File "/home/meraj/anaconda3/envs/analysis/lib/python3.10/site-packages/liftoff/polish.py", line 157, in matches_ref
    ref_cds_seq = get_seq(ref_cds_group, ref_fa)
  File "/home/meraj/anaconda3/envs/analysis/lib/python3.10/site-packages/liftoff/polish.py", line 129, in get_seq
    chrom_seq = fasta_index[cds_group[0].seqid]
IndexError: list index out of range

The gff3 and fasta files are downloaded from NCBI nucleotide database [GenBank accessions: AM884177.2 and NC_010287.1] .

I have tried with and without feature list (-f) with no success. 
I tried looking for formatting errors in my fasta and gff files but I could not find any.
I checked if the directory is writable, and it is.  

I have attached the files I am using.

Thank you for your time
Symeriz

[liftoffFiles.zip](https://github.com/agshumate/Liftoff/files/10273711/liftoffFiles.zip)
